// swift-tools-version:5.3

import PackageDescription

let package = Package(
    name: "HighlightrWidgy",
    platforms: [
        .macOS(.v12_0),
        .iOS(.v14),
    ],
    products: [
        .library(name: "HighlightrWidgy", targets: ["HighlightrWidgy"])
    ],
    dependencies: [],
    targets: [
        .target(
            name: "HighlightrWidgy",
            dependencies: [],
            path: "Sources",
            exclude: [],
            sources: [
                "Classes",
            ],
            resources: [
                .copy("Assets/highlight.min.js"),
                .copy("Assets/a11y-dark.min.css"),
                .copy("Assets/a11y-light.min.css"),
                .copy("Assets/agate.min.css"),
                .copy("Assets/an-old-hope.min.css"),
                .copy("Assets/androidstudio.min.css"),
                .copy("Assets/arduino-light.min.css"),
                .copy("Assets/arta.min.css"),
                .copy("Assets/ascetic.min.css"),
                .copy("Assets/atelier-cave-dark.min.css"),
                .copy("Assets/atelier-cave-light.min.css"),
                .copy("Assets/atelier-dune-dark.min.css"),
                .copy("Assets/atelier-dune-light.min.css"),
                .copy("Assets/atelier-estuary-dark.min.css"),
                .copy("Assets/atelier-estuary-light.min.css"),
                .copy("Assets/atelier-forest-dark.min.css"),
                .copy("Assets/atelier-forest-light.min.css"),
                .copy("Assets/atelier-heath-dark.min.css"),
                .copy("Assets/atelier-heath-light.min.css"),
                .copy("Assets/atelier-lakeside-dark.min.css"),
                .copy("Assets/atelier-lakeside-light.min.css"),
                .copy("Assets/atelier-plateau-dark.min.css"),
                .copy("Assets/atelier-plateau-light.min.css"),
                .copy("Assets/atelier-savanna-dark.min.css"),
                .copy("Assets/atelier-savanna-light.min.css"),
                .copy("Assets/atelier-seaside-dark.min.css"),
                .copy("Assets/atelier-seaside-light.min.css"),
                .copy("Assets/atelier-sulphurpool-dark.min.css"),
                .copy("Assets/atelier-sulphurpool-light.min.css"),
                .copy("Assets/atom-one-dark-reasonable.min.css"),
                .copy("Assets/atom-one-dark.min.css"),
                .copy("Assets/atom-one-light.min.css"),
                .copy("Assets/brown-paper.min.css"),
                .copy("Assets/codepen-embed.min.css"),
                .copy("Assets/color-brewer.min.css"),
                .copy("Assets/darcula.min.css"),
                .copy("Assets/dark.min.css"),
                .copy("Assets/darkula.min.css"),
                .copy("Assets/default.min.css"),
                .copy("Assets/docco.min.css"),
                .copy("Assets/dracula.min.css"),
                .copy("Assets/far.min.css"),
                .copy("Assets/foundation.min.css"),
                .copy("Assets/github-gist.min.css"),
                .copy("Assets/github.min.css"),
                .copy("Assets/gml.min.css"),
                .copy("Assets/googlecode.min.css"),
                .copy("Assets/grayscale.min.css"),
                .copy("Assets/gruvbox-dark.min.css"),
                .copy("Assets/gruvbox-light.min.css"),
                .copy("Assets/hopscotch.min.css"),
                .copy("Assets/hybrid.min.css"),
                .copy("Assets/idea.min.css"),
                .copy("Assets/ir-black.min.css"),
                .copy("Assets/isbl-editor-dark.min.css"),
                .copy("Assets/isbl-editor-light.min.css"),
                .copy("Assets/kimbie.dark.min.css"),
                .copy("Assets/kimbie.light.min.css"),
                .copy("Assets/lightfair.min.css"),
                .copy("Assets/magula.min.css"),
                .copy("Assets/mono-blue.min.css"),
                .copy("Assets/monokai-sublime.min.css"),
                .copy("Assets/monokai.min.css"),
                .copy("Assets/nord.min.css"),
                .copy("Assets/obsidian.min.css"),
                .copy("Assets/ocean.min.css"),
                .copy("Assets/paraiso-dark.min.css"),
                .copy("Assets/paraiso-light.min.css"),
                .copy("Assets/pojoaque.min.css"),
                .copy("Assets/purebasic.min.css"),
                .copy("Assets/qtcreator_dark.min.css"),
                .copy("Assets/qtcreator_light.min.css"),
                .copy("Assets/railscasts.min.css"),
                .copy("Assets/rainbow.min.css"),
                .copy("Assets/routeros.min.css"),
                .copy("Assets/school-book.min.css"),
                .copy("Assets/shades-of-purple.min.css"),
                .copy("Assets/solarized-dark.min.css"),
                .copy("Assets/solarized-light.min.css"),
                .copy("Assets/sunburst.min.css"),
                .copy("Assets/tomorrow-night-blue.min.css"),
                .copy("Assets/tomorrow-night-bright.min.css"),
                .copy("Assets/tomorrow-night-eighties.min.css"),
                .copy("Assets/tomorrow-night.min.css"),
                .copy("Assets/tomorrow.min.css"),
                .copy("Assets/vs.min.css"),
                .copy("Assets/vs2015.min.css"),
                .copy("Assets/xcode.min.css"),
                .copy("Assets/xt256.min.css"),
                .copy("Assets/zenburn.min.css"),
            ]
        ),
    ]
)
